// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

const s3Client = new S3Client({ region: process.env.AWS_REGION });

interface ResourceProperties {
  BucketName: string;
  CognitoRegion: string;
  UserPoolId: string;
  UserPoolClientId: string;
  ApiEndpoint: string;
  Timestamp?: string;
}

interface CustomResourceEvent {
  RequestType: "Create" | "Update" | "Delete";
  ResourceProperties: ResourceProperties;
  PhysicalResourceId?: string;
  StackId: string;
  RequestId: string;
  LogicalResourceId: string;
  ResponseURL: string;
}

export const handler = async (event: CustomResourceEvent): Promise<any> => {
  console.log("Event:", JSON.stringify(event, null, 2));

  const {
    BucketName,
    CognitoRegion,
    UserPoolId,
    UserPoolClientId,
    ApiEndpoint,
  } = event.ResourceProperties;

  const configContent = `// Auto-generated configuration - DO NOT EDIT
// Generated by CDK deployment
window.APP_CONFIG = {
  COGNITO_REGION: '${CognitoRegion}',
  COGNITO_USER_POOL_ID: '${UserPoolId}',
  COGNITO_USER_POOL_WEB_CLIENT_ID: '${UserPoolClientId}',
  API_ENDPOINT: '${ApiEndpoint}'
};
`;

  try {
    if (event.RequestType === "Delete") {
      console.log("Delete request - skipping config.js deletion");
      return {
        PhysicalResourceId: event.PhysicalResourceId || "config-writer",
      };
    }

    // Write config.js to S3
    const command = new PutObjectCommand({
      Bucket: BucketName,
      Key: "config.js",
      Body: configContent,
      ContentType: "application/javascript",
      CacheControl: "no-cache, no-store, must-revalidate",
    });

    const result = await s3Client.send(command);

    return {
      PhysicalResourceId: "config-writer",
      Data: {
        Message: "Config file written successfully",
      },
    };
  } catch (error) {
    console.error("Error writing config.js:", error);
    throw error;
  }
};
